name: Issue
description: Report an issue with the dots
labels: ["bug"]
type: "Bug"
title: "[BUG] "
body:
    - type: markdown
      attributes:
          value: "**Welcome to submit a new issue!**\n- It takes only 3 steps, so please be patient :)\n- Tip: If your issue is not a feature request and is not an issue with the dots (e.g. \"how do I use X feature\"), please use [Discussions](https://github.com/caelestia-dots/shell/discussions) instead."
    - type: checkboxes
      attributes:
          label: "Step 1. Before you submit"
          description: "Hint: The 2nd and 3rd checkbox is **not** forcely required as you may have failed to do so."
          options:
              - label: I have read the above instructions and am sure that this is supposed to be posted here.
                required: true
              - label: I've successfully updated to the latest versions following the [updating guide](https://github.com/caelestia-dots/caelestia?tab=readme-ov-file#updating).
                required: false # Not required cuz user may have failed to do so
              - label: I've successfully updated the system packages to the latest.
                required: false # Not required cuz user may have failed to do so
              - label: I've ticked the checkboxes without reading their contents
                required: false # Obviously

    - type: textarea
      attributes:
          label: "Step 2. Version info"
          description: "Run `caelestia -v` and paste the result below."
          value: "<details><summary>Version info</summary>\n\n```\n<!-- Run `caelestia -v` and paste the result here! -->\n```\n\n</details>"
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              **Tips for the following Step 3**
              1. Use `LANG=C LC_ALL=C` to get the output of a command in English, eg. `LANG=C LC_ALL=C date` displays time in English.
              2. If it throws errors, **PLEASE**, attach logs and describe in detail if possible.
                 - Something happened to the shell (bar, dashboard, etc)? Run `caelestia shell -l` WITHOUT exiting the shell for logs.
                 - Installation failed? Run installation again for logs.
                 - You may use more code blocks when needed.
              3. In case you are confused, the `<details>`, `<summary>`, `</summary>`, `</details>` are HTML tags for folding the logs (typically very long) inside. Please do not touch them (unless you know what you are doing).
              4. If the logs are suuuuuuper long, consider using an online pastebin service instead.

    - type: textarea
      attributes:
          label: "Step 3. Describe the issue"
          value: "\n<!-- Firsly describe your issue here! -->\n\n<details><summary>Logs</summary>\n\n```\n<!-- Put your log content here!-->\n```\n\n</details>"
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Reminder
          options:
              - label: I agree that it's usually impossible for others to help me without my logs.
                required: true
